import { Metadata } from "next"
import styles from "./styles.module.css"

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <nav className="flex justify-center align-middle bg-slate-600">
        <div className="inset-0 text-xl">About NavBar</div>
      </nav>
      <main className={styles.main}>{children}</main>
    </>
  )
}
